// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package chatproto is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	ReqChatText
	ReqChatHistory
	S2C_ChatText
	S2C_ChatHistory
*/
package chatproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqChatText struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Channel int32  `protobuf:"varint,2,opt,name=Channel" json:"Channel,omitempty"`
}

func (m *ReqChatText) Reset()                    { *m = ReqChatText{} }
func (m *ReqChatText) String() string            { return proto.CompactTextString(m) }
func (*ReqChatText) ProtoMessage()               {}
func (*ReqChatText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqChatText) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReqChatText) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type ReqChatHistory struct {
	Channel int32 `protobuf:"varint,1,opt,name=Channel" json:"Channel,omitempty"`
}

func (m *ReqChatHistory) Reset()                    { *m = ReqChatHistory{} }
func (m *ReqChatHistory) String() string            { return proto.CompactTextString(m) }
func (*ReqChatHistory) ProtoMessage()               {}
func (*ReqChatHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqChatHistory) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

// ===========S2C=========
type S2C_ChatText struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Channel int32  `protobuf:"varint,2,opt,name=Channel" json:"Channel,omitempty"`
	RoleId  int64  `protobuf:"varint,3,opt,name=RoleId" json:"RoleId,omitempty"`
	Date    uint32 `protobuf:"fixed32,4,opt,name=Date" json:"Date,omitempty"`
}

func (m *S2C_ChatText) Reset()                    { *m = S2C_ChatText{} }
func (m *S2C_ChatText) String() string            { return proto.CompactTextString(m) }
func (*S2C_ChatText) ProtoMessage()               {}
func (*S2C_ChatText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2C_ChatText) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *S2C_ChatText) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *S2C_ChatText) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *S2C_ChatText) GetDate() uint32 {
	if m != nil {
		return m.Date
	}
	return 0
}

type S2C_ChatHistory struct {
	Channel int32         `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	History *S2C_ChatText `protobuf:"bytes,2,opt,name=history" json:"history,omitempty"`
}

func (m *S2C_ChatHistory) Reset()                    { *m = S2C_ChatHistory{} }
func (m *S2C_ChatHistory) String() string            { return proto.CompactTextString(m) }
func (*S2C_ChatHistory) ProtoMessage()               {}
func (*S2C_ChatHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2C_ChatHistory) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *S2C_ChatHistory) GetHistory() *S2C_ChatText {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqChatText)(nil), "chatproto.ReqChatText")
	proto.RegisterType((*ReqChatHistory)(nil), "chatproto.ReqChatHistory")
	proto.RegisterType((*S2C_ChatText)(nil), "chatproto.S2C_ChatText")
	proto.RegisterType((*S2C_ChatHistory)(nil), "chatproto.S2C_ChatHistory")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x47, 0x2e, 0xee,
	0xa0, 0xd4, 0x42, 0xe7, 0x8c, 0xc4, 0x92, 0x90, 0xd4, 0x8a, 0x12, 0x21, 0x09, 0x2e, 0x76, 0xe7,
	0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x17, 0x2c,
	0x93, 0x91, 0x98, 0x97, 0x97, 0x9a, 0x23, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe3, 0x2a,
	0x69, 0x71, 0xf1, 0x41, 0x8d, 0xf0, 0xc8, 0x2c, 0x2e, 0xc9, 0x2f, 0xaa, 0x44, 0x56, 0xcb, 0x88,
	0xaa, 0x36, 0x8f, 0x8b, 0x27, 0xd8, 0xc8, 0x39, 0x9e, 0x12, 0xfb, 0x84, 0xc4, 0xb8, 0xd8, 0x82,
	0xf2, 0x73, 0x52, 0x3d, 0x53, 0x24, 0x98, 0x15, 0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21, 0x21,
	0x2e, 0x16, 0x97, 0xc4, 0x92, 0x54, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xf6, 0x20, 0x30, 0x5b, 0x29,
	0x8e, 0x8b, 0x1f, 0x66, 0x1f, 0x92, 0xe3, 0x92, 0x51, 0x1d, 0x07, 0xe5, 0x0a, 0x19, 0x72, 0xb1,
	0x67, 0x40, 0x14, 0x81, 0xad, 0xe4, 0x36, 0x12, 0xd7, 0x83, 0x07, 0x94, 0x1e, 0xb2, 0xb3, 0x83,
	0x60, 0xea, 0x92, 0xd8, 0xc0, 0x92, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x88, 0x3e,
	0x73, 0x5e, 0x01, 0x00, 0x00,
}
