// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: base.proto
using System;

namespace proto
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Echo")]
	public partial class Echo : global::ProtoBuf.IExtensible
	{
		public Echo() {}
		
		string _content = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string content
		{
			get { return _content; }
			set { _content = value; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
