// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package chatproto is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	CSChatText
	CSChatHistory
	SCChatText
	SCChatHistory
*/
package chatproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CSChatText struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Channel int32  `protobuf:"varint,2,opt,name=Channel" json:"Channel,omitempty"`
}

func (m *CSChatText) Reset()                    { *m = CSChatText{} }
func (m *CSChatText) String() string            { return proto.CompactTextString(m) }
func (*CSChatText) ProtoMessage()               {}
func (*CSChatText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CSChatText) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CSChatText) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type CSChatHistory struct {
	Channel int32 `protobuf:"varint,1,opt,name=Channel" json:"Channel,omitempty"`
}

func (m *CSChatHistory) Reset()                    { *m = CSChatHistory{} }
func (m *CSChatHistory) String() string            { return proto.CompactTextString(m) }
func (*CSChatHistory) ProtoMessage()               {}
func (*CSChatHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CSChatHistory) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

// ===========S2C=========
type SCChatText struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Channel int32  `protobuf:"varint,2,opt,name=Channel" json:"Channel,omitempty"`
	RoleId  int64  `protobuf:"varint,3,opt,name=RoleId" json:"RoleId,omitempty"`
	Date    uint32 `protobuf:"fixed32,4,opt,name=Date" json:"Date,omitempty"`
}

func (m *SCChatText) Reset()                    { *m = SCChatText{} }
func (m *SCChatText) String() string            { return proto.CompactTextString(m) }
func (*SCChatText) ProtoMessage()               {}
func (*SCChatText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SCChatText) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SCChatText) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SCChatText) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *SCChatText) GetDate() uint32 {
	if m != nil {
		return m.Date
	}
	return 0
}

type SCChatHistory struct {
	Channel int32       `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	History *SCChatText `protobuf:"bytes,2,opt,name=history" json:"history,omitempty"`
}

func (m *SCChatHistory) Reset()                    { *m = SCChatHistory{} }
func (m *SCChatHistory) String() string            { return proto.CompactTextString(m) }
func (*SCChatHistory) ProtoMessage()               {}
func (*SCChatHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SCChatHistory) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SCChatHistory) GetHistory() *SCChatText {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterType((*CSChatText)(nil), "chatproto.CSChatText")
	proto.RegisterType((*CSChatHistory)(nil), "chatproto.CSChatHistory")
	proto.RegisterType((*SCChatText)(nil), "chatproto.SCChatText")
	proto.RegisterType((*SCChatHistory)(nil), "chatproto.SCChatHistory")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x07, 0x2e, 0x2e,
	0xe7, 0x60, 0xe7, 0x8c, 0xc4, 0x92, 0x90, 0xd4, 0x8a, 0x12, 0x21, 0x09, 0x2e, 0x76, 0xe7, 0xfc,
	0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x17, 0x2c, 0x93,
	0x91, 0x98, 0x97, 0x97, 0x9a, 0x23, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe3, 0x2a, 0x69,
	0x72, 0xf1, 0x42, 0x4c, 0xf0, 0xc8, 0x2c, 0x2e, 0xc9, 0x2f, 0xaa, 0x44, 0x56, 0xca, 0x88, 0xaa,
	0x34, 0x87, 0x8b, 0x2b, 0xd8, 0x99, 0x12, 0xcb, 0x84, 0xc4, 0xb8, 0xd8, 0x82, 0xf2, 0x73, 0x52,
	0x3d, 0x53, 0x24, 0x98, 0x15, 0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21, 0x21, 0x2e, 0x16, 0x97,
	0xc4, 0x92, 0x54, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xf6, 0x20, 0x30, 0x5b, 0x29, 0x8a, 0x8b, 0x17,
	0x62, 0x1b, 0x92, 0xc3, 0x92, 0x51, 0x1d, 0x06, 0xe5, 0x0a, 0xe9, 0x73, 0xb1, 0x67, 0x40, 0x14,
	0x81, 0x2d, 0xe4, 0x36, 0x12, 0xd5, 0x83, 0x07, 0x91, 0x1e, 0xc2, 0xc9, 0x41, 0x30, 0x55, 0x49,
	0x6c, 0x60, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xf6, 0xd1, 0xc0, 0x56, 0x01,
	0x00, 0x00,
}
