// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: chat.proto

package chatproto

import (
	"github.com/davyxu/cellnet"
	"reflect"
	_ "github.com/davyxu/cellnet/codec/pb"
)

func init() {

	// chat.proto
	cellnet.RegisterMessageMeta("pb", "chatproto.CSChatText", reflect.TypeOf((*CSChatText)(nil)).Elem(), 3357223834)
	cellnet.RegisterMessageMeta("pb", "chatproto.CSChatHistory", reflect.TypeOf((*CSChatHistory)(nil)).Elem(), 772284261)
	cellnet.RegisterMessageMeta("pb", "chatproto.SCChatText", reflect.TypeOf((*SCChatText)(nil)).Elem(), 3529489778)
	cellnet.RegisterMessageMeta("pb", "chatproto.SCChatHistory", reflect.TypeOf((*SCChatHistory)(nil)).Elem(), 1991199256)

}
