// Generated by cat/proto/gen_proto.py
// DO NOT EDIT!
// Gen Time: 2019-08-15 09:05:02

using AM.Game;

namespace Proto {

	public enum Keys {
		// ===========S2C=========
		SCChatText = 56829,
		// 测试Echo
		Echo = 13441,
		// 服务端要求回答口令
		SCEntryAlias = 16116,
		// 客户端回答口令
		CSEntryToken = 6187,
		// 提示
		SCNotice = 44314,
		// 文本提示
		SCNoticeText = 10751,
		// 默认响应
		SCResponse = 4871,
		// 错误，0是无错误
		SCError = 48898,
		// 角色进入游戏
		CSRoleEnter = 10888,
	}

	public static class ProtoMsg {
		public static void init() {
			MsgMetaSet.RegMsg(56829, typeof(SCChatText), ()=>new SCChatText());
			MsgMetaSet.RegMsg(13441, typeof(Echo), ()=>new Echo());
			MsgMetaSet.RegMsg(16116, typeof(SCEntryAlias), ()=>new SCEntryAlias());
			MsgMetaSet.RegMsg(6187, typeof(CSEntryToken), ()=>new CSEntryToken());
			MsgMetaSet.RegMsg(44314, typeof(SCNotice), ()=>new SCNotice());
			MsgMetaSet.RegMsg(10751, typeof(SCNoticeText), ()=>new SCNoticeText());
			MsgMetaSet.RegMsg(4871, typeof(SCResponse), ()=>new SCResponse());
			MsgMetaSet.RegMsg(48898, typeof(SCError), ()=>new SCError());
			MsgMetaSet.RegMsg(10888, typeof(CSRoleEnter), ()=>new CSRoleEnter());
		}
	}
}
