// Generated by cat/proto/gen_proto.py
// DO NOT EDIT!
// Gen Time: 2019-08-17 16:22:50

using AM.Game;

namespace Proto {

	public enum Keys {
		
		CSChatText = 56317,
		
		CSChatHistory = 5034,
		// ===========S2C=========
		SCChatText = 56829,
		
		SCChatHistory = 54698,
		// 测试Echo
		Echo = 13441,
		// 服务端要求回答口令
		SCEntryAlias = 16116,
		// 客户端回答口令
		CSEntryToken = 6187,
		// 提示
		SCNotice = 44314,
		// 文本提示
		SCNoticeText = 10751,
		// 默认响应
		SCResponse = 4871,
		// 错误，0是无错误
		SCError = 48898,
		
		RPCMsg = 25198,
		// 创建账号
		AccountCreate = 62915,
		
		AccountLogin = 38152,
		
		RoleCreate = 19784,
		// 角色进入游戏
		CSRoleEnter = 10888,
	}

	public static class ProtoMsg {
		public static void init() {
			MsgMetaSet.RegMsg(56317, typeof(CSChatText), ()=>new CSChatText());
			MsgMetaSet.RegMsg(5034, typeof(CSChatHistory), ()=>new CSChatHistory());
			MsgMetaSet.RegMsg(56829, typeof(SCChatText), ()=>new SCChatText());
			MsgMetaSet.RegMsg(54698, typeof(SCChatHistory), ()=>new SCChatHistory());
			MsgMetaSet.RegMsg(13441, typeof(Echo), ()=>new Echo());
			MsgMetaSet.RegMsg(16116, typeof(SCEntryAlias), ()=>new SCEntryAlias());
			MsgMetaSet.RegMsg(6187, typeof(CSEntryToken), ()=>new CSEntryToken());
			MsgMetaSet.RegMsg(44314, typeof(SCNotice), ()=>new SCNotice());
			MsgMetaSet.RegMsg(10751, typeof(SCNoticeText), ()=>new SCNoticeText());
			MsgMetaSet.RegMsg(4871, typeof(SCResponse), ()=>new SCResponse());
			MsgMetaSet.RegMsg(48898, typeof(SCError), ()=>new SCError());
			MsgMetaSet.RegMsg(25198, typeof(RPCMsg), ()=>new RPCMsg());
			MsgMetaSet.RegMsg(62915, typeof(AccountCreate), ()=>new AccountCreate());
			MsgMetaSet.RegMsg(38152, typeof(AccountLogin), ()=>new AccountLogin());
			MsgMetaSet.RegMsg(19784, typeof(RoleCreate), ()=>new RoleCreate());
			MsgMetaSet.RegMsg(10888, typeof(CSRoleEnter), ()=>new CSRoleEnter());
		}
	}
}
