// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package loginproto is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	CSToken
	SCToken
	CSLogin
	SCLogin
	CSRoleList
	SCRoleList
	CSLoginRole
	SCLoginRole
*/
package loginproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CSToken struct {
}

func (m *CSToken) Reset()                    { *m = CSToken{} }
func (m *CSToken) String() string            { return proto.CompactTextString(m) }
func (*CSToken) ProtoMessage()               {}
func (*CSToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SCToken struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *SCToken) Reset()                    { *m = SCToken{} }
func (m *SCToken) String() string            { return proto.CompactTextString(m) }
func (*SCToken) ProtoMessage()               {}
func (*SCToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SCToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CSLogin struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CSLogin) Reset()                    { *m = CSLogin{} }
func (m *CSLogin) String() string            { return proto.CompactTextString(m) }
func (*CSLogin) ProtoMessage()               {}
func (*CSLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CSLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CSLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SCLogin struct {
	Error int32 `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
}

func (m *SCLogin) Reset()                    { *m = SCLogin{} }
func (m *SCLogin) String() string            { return proto.CompactTextString(m) }
func (*SCLogin) ProtoMessage()               {}
func (*SCLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SCLogin) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type CSRoleList struct {
}

func (m *CSRoleList) Reset()                    { *m = CSRoleList{} }
func (m *CSRoleList) String() string            { return proto.CompactTextString(m) }
func (*CSRoleList) ProtoMessage()               {}
func (*CSRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SCRoleList struct {
	Roles []*proto1.RoleBase `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *SCRoleList) Reset()                    { *m = SCRoleList{} }
func (m *SCRoleList) String() string            { return proto.CompactTextString(m) }
func (*SCRoleList) ProtoMessage()               {}
func (*SCRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SCRoleList) GetRoles() []*proto1.RoleBase {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CSLoginRole struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CSLoginRole) Reset()                    { *m = CSLoginRole{} }
func (m *CSLoginRole) String() string            { return proto.CompactTextString(m) }
func (*CSLoginRole) ProtoMessage()               {}
func (*CSLoginRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CSLoginRole) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SCLoginRole struct {
	Error int32 `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
}

func (m *SCLoginRole) Reset()                    { *m = SCLoginRole{} }
func (m *SCLoginRole) String() string            { return proto.CompactTextString(m) }
func (*SCLoginRole) ProtoMessage()               {}
func (*SCLoginRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SCLoginRole) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func init() {
	proto.RegisterType((*CSToken)(nil), "loginproto.CSToken")
	proto.RegisterType((*SCToken)(nil), "loginproto.SCToken")
	proto.RegisterType((*CSLogin)(nil), "loginproto.CSLogin")
	proto.RegisterType((*SCLogin)(nil), "loginproto.SCLogin")
	proto.RegisterType((*CSRoleList)(nil), "loginproto.CSRoleList")
	proto.RegisterType((*SCRoleList)(nil), "loginproto.SCRoleList")
	proto.RegisterType((*CSLoginRole)(nil), "loginproto.CSLoginRole")
	proto.RegisterType((*SCLoginRole)(nil), "loginproto.SCLoginRole")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xc1, 0x4a, 0xc4, 0x30,
	0x18, 0x84, 0x69, 0x4b, 0x2d, 0x3b, 0x15, 0x95, 0xb8, 0x87, 0x20, 0x88, 0x4b, 0x44, 0xd8, 0xd3,
	0x0a, 0x2e, 0xbe, 0x80, 0xb9, 0xee, 0x29, 0xf1, 0x05, 0xd6, 0x36, 0x48, 0xb0, 0xf4, 0x5f, 0x92,
	0x2c, 0xbe, 0xbe, 0xe4, 0x4f, 0xf7, 0xe6, 0xa9, 0xf3, 0x75, 0xe6, 0x9f, 0x0c, 0xfa, 0x89, 0xbe,
	0xfd, 0xbc, 0x3b, 0x05, 0x4a, 0x24, 0xc0, 0xc0, 0xfa, 0xe1, 0x9e, 0x3f, 0xaf, 0x31, 0x85, 0xf3,
	0x90, 0x62, 0x09, 0xa8, 0x15, 0x3a, 0x6d, 0x3f, 0xe9, 0xc7, 0xcd, 0xea, 0x09, 0x9d, 0xd5, 0x2c,
	0xc5, 0x1a, 0x6d, 0xca, 0x42, 0x56, 0x9b, 0x6a, 0xbb, 0x32, 0x05, 0xd4, 0x7b, 0xce, 0x1e, 0x72,
	0xa1, 0x90, 0xe8, 0x8e, 0xc3, 0x40, 0xe7, 0x39, 0x2d, 0x91, 0x0b, 0x8a, 0x3b, 0x34, 0xa7, 0xdf,
	0x51, 0xd6, 0xfc, 0x37, 0xcb, 0xd2, 0x5b, 0xce, 0xd6, 0x68, 0x5d, 0x08, 0x14, 0xf8, 0xa8, 0x35,
	0x05, 0xd4, 0x35, 0xa0, 0xad, 0xa1, 0xc9, 0x1d, 0x7c, 0x4c, 0x6a, 0x0f, 0x58, 0x7d, 0x21, 0xf1,
	0x82, 0x36, 0xd0, 0xe4, 0xa2, 0xac, 0x36, 0xcd, 0xb6, 0x7f, 0xbb, 0x2d, 0xb3, 0x77, 0xd9, 0xff,
	0x38, 0x46, 0x67, 0x8a, 0xab, 0x1e, 0xd1, 0x2f, 0xd3, 0xb2, 0x23, 0x6e, 0x50, 0xfb, 0x91, 0x1f,
	0x69, 0x4c, 0xed, 0x47, 0xf5, 0x8c, 0x7e, 0x99, 0xc0, 0xf6, 0xbf, 0x33, 0xbe, 0xae, 0xb8, 0x7a,
	0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x13, 0xdf, 0xa8, 0xd9, 0x41, 0x01, 0x00, 0x00,
}
