// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package loginproto is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	SCCheck
	CSLogin
	SCLogin
	CSRoleList
	SCRoleList
	CSLoginRole
	SCLoginRole
*/
package loginproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import roleproto "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SCCheck struct {
	PublicKey string `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
}

func (m *SCCheck) Reset()                    { *m = SCCheck{} }
func (m *SCCheck) String() string            { return proto.CompactTextString(m) }
func (*SCCheck) ProtoMessage()               {}
func (*SCCheck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SCCheck) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type CSLogin struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CSLogin) Reset()                    { *m = CSLogin{} }
func (m *CSLogin) String() string            { return proto.CompactTextString(m) }
func (*CSLogin) ProtoMessage()               {}
func (*CSLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CSLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CSLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SCLogin struct {
	Error int32 `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
}

func (m *SCLogin) Reset()                    { *m = SCLogin{} }
func (m *SCLogin) String() string            { return proto.CompactTextString(m) }
func (*SCLogin) ProtoMessage()               {}
func (*SCLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SCLogin) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type CSRoleList struct {
}

func (m *CSRoleList) Reset()                    { *m = CSRoleList{} }
func (m *CSRoleList) String() string            { return proto.CompactTextString(m) }
func (*CSRoleList) ProtoMessage()               {}
func (*CSRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SCRoleList struct {
	Roles []*roleproto.RoleBase `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *SCRoleList) Reset()                    { *m = SCRoleList{} }
func (m *SCRoleList) String() string            { return proto.CompactTextString(m) }
func (*SCRoleList) ProtoMessage()               {}
func (*SCRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SCRoleList) GetRoles() []*roleproto.RoleBase {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CSLoginRole struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CSLoginRole) Reset()                    { *m = CSLoginRole{} }
func (m *CSLoginRole) String() string            { return proto.CompactTextString(m) }
func (*CSLoginRole) ProtoMessage()               {}
func (*CSLoginRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CSLoginRole) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SCLoginRole struct {
	Error int32 `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
}

func (m *SCLoginRole) Reset()                    { *m = SCLoginRole{} }
func (m *SCLoginRole) String() string            { return proto.CompactTextString(m) }
func (*SCLoginRole) ProtoMessage()               {}
func (*SCLoginRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SCLoginRole) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func init() {
	proto.RegisterType((*SCCheck)(nil), "loginproto.SCCheck")
	proto.RegisterType((*CSLogin)(nil), "loginproto.CSLogin")
	proto.RegisterType((*SCLogin)(nil), "loginproto.SCLogin")
	proto.RegisterType((*CSRoleList)(nil), "loginproto.CSRoleList")
	proto.RegisterType((*SCRoleList)(nil), "loginproto.SCRoleList")
	proto.RegisterType((*CSLoginRole)(nil), "loginproto.CSLoginRole")
	proto.RegisterType((*SCLoginRole)(nil), "loginproto.SCLoginRole")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x4b, 0x2d, 0xfb, 0x2a, 0x22, 0xd1, 0x43, 0x10, 0xc5, 0x25, 0x1e, 0x5c, 0x2f,
	0x3d, 0x28, 0xe2, 0xdd, 0x1c, 0xdd, 0x53, 0xf2, 0x0b, 0x76, 0xd3, 0xa0, 0xc1, 0xb0, 0x29, 0x69,
	0x17, 0xf1, 0xdf, 0x4b, 0x26, 0x2d, 0x5e, 0xf6, 0x36, 0xef, 0xcd, 0x9b, 0x37, 0x1f, 0x5a, 0x1f,
	0x3e, 0xdd, 0xa1, 0x1b, 0x62, 0x98, 0x02, 0x03, 0x09, 0x9a, 0x6f, 0x10, 0x83, 0xb7, 0xd9, 0x17,
	0x8f, 0x68, 0xb4, 0x94, 0x5f, 0xd6, 0x7c, 0xb3, 0x5b, 0xac, 0x86, 0xe3, 0xde, 0x3b, 0xf3, 0x61,
	0x7f, 0x79, 0xb1, 0x2e, 0x36, 0x2b, 0xf5, 0x6f, 0x88, 0x57, 0x34, 0x52, 0x6f, 0x53, 0x09, 0xe3,
	0x68, 0x76, 0xc6, 0x84, 0xe3, 0x61, 0x9a, 0x63, 0x8b, 0x64, 0x97, 0xa8, 0x86, 0x9f, 0x9e, 0x97,
	0xe4, 0xa6, 0x51, 0xdc, 0xa7, 0xfe, 0x7c, 0x76, 0x8d, 0xda, 0xc6, 0x18, 0x22, 0x1d, 0xd5, 0x2a,
	0x0b, 0x71, 0x0e, 0x48, 0xad, 0x82, 0xb7, 0x5b, 0x37, 0x4e, 0xe2, 0x0d, 0xd0, 0x72, 0x51, 0xec,
	0x09, 0x75, 0x42, 0x1d, 0x79, 0xb1, 0xae, 0x36, 0xed, 0xf3, 0x55, 0x97, 0x14, 0x71, 0x77, 0x29,
	0xf3, 0xbe, 0x1b, 0xad, 0xca, 0x09, 0x71, 0x87, 0x76, 0xc6, 0x4b, 0x1b, 0x76, 0x81, 0xd2, 0xf5,
	0xf4, 0xa8, 0x52, 0xa5, 0xeb, 0xc5, 0x03, 0xda, 0x19, 0x83, 0xd6, 0x27, 0x51, 0xf6, 0x67, 0x54,
	0xfd, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff, 0x35, 0xd0, 0x12, 0xe6, 0x39, 0x01, 0x00, 0x00,
}
