// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: login.proto

package loginproto

import (
	"github.com/davyxu/cellnet"
	"reflect"
	_ "github.com/davyxu/cellnet/codec/pb"
)

func init() {

	// login.proto
	cellnet.RegisterMessageMeta("pb", "loginproto.CSCheck", reflect.TypeOf((*CSCheck)(nil)).Elem(), 1800968233)
	cellnet.RegisterMessageMeta("pb", "loginproto.CSLogin", reflect.TypeOf((*CSLogin)(nil)).Elem(), 4049841973)
	cellnet.RegisterMessageMeta("pb", "loginproto.CSLoginRole", reflect.TypeOf((*CSLoginRole)(nil)).Elem(), 4251931294)

}
