// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: role.proto
// Source: login.proto

package roleproto

import (
	"github.com/davyxu/cellnet"
	"reflect"
	_ "github.com/davyxu/cellnet/codec/pb"
)

func init() {

	// role.proto
	cellnet.RegisterMessageMeta("pb", "roleproto.RoleBase", reflect.TypeOf((*RoleBase)(nil)).Elem(), 1385219412)

	// login.proto
	cellnet.RegisterMessageMeta("pb", "loginproto.SCCheck", reflect.TypeOf((*SCCheck)(nil)).Elem(), 4003282643)
	cellnet.RegisterMessageMeta("pb", "loginproto.CSLogin", reflect.TypeOf((*CSLogin)(nil)).Elem(), 4049841973)
	cellnet.RegisterMessageMeta("pb", "loginproto.SCLogin", reflect.TypeOf((*SCLogin)(nil)).Elem(), 1957038543)
	cellnet.RegisterMessageMeta("pb", "loginproto.CSRoleList", reflect.TypeOf((*CSRoleList)(nil)).Elem(), 305111222)
	cellnet.RegisterMessageMeta("pb", "loginproto.SCRoleList", reflect.TypeOf((*SCRoleList)(nil)).Elem(), 141243998)
	cellnet.RegisterMessageMeta("pb", "loginproto.CSLoginRole", reflect.TypeOf((*CSLoginRole)(nil)).Elem(), 4251931294)
	cellnet.RegisterMessageMeta("pb", "loginproto.SCLoginRole", reflect.TypeOf((*SCLoginRole)(nil)).Elem(), 517266889)

}
