* 设定
** 区域地形
世界分为复兴区和混沌区。可生存区域是复苏的区域，这部分实际只占所有面积的一小部分，大部分区域都无法生存，也未有人探索过。未探索区有着很多潜在的危险，比如高辐射，混乱的机械生物，没有食物，迷路。生存区分为五个城市，位于东面沿海之角为旸城，西南有斐南，中有神原，北有云州，西有白都。旸城有温泉，斐南有美食，白都有白河与传说。
** 物种组成
+ 兽人。并且占据了世界的重要部分，不知道如何出现的，其外形和普通人类大致相同，但身上却有类似某些动物的特状，主要以耳朵和尾巴，角，翅膀，头发为特点。主要以猫，狗，兔子类比较多，其习性有部分动物的类似之处。
+ 深渊生物。某个时刻起，从混沌区域出现的怪物，它们频繁地向圈内聚集，并破坏设施，伤害原居民。这类生物全身体形各异，以四足兽为主，大部分全身覆盖有白色外壳，更有少数有非常坚硬的盾甲。最开始，这类入侵比较无规律，次数虽然多，但规模不大。兽人在与怪物的对抗中，渐渐占据上风。并形成了相关职业专门从事对抗怪物这一工作。
+ 人类。虽然把人类和兽人分开列出了，但实际人和兽人是混居在一起，与其分开不如归为一类更合适。
+ 动物。小型花豹，猫，狼，马，狗，羊。
** 有名的社团
*** 神之花观测组
主要是记录神花的行为和研究其内在规律。存在时间最长的一个团体。目前的有几点结论：
+ 大危机！神花的扩展速度正在下降。在很长的一段时间内，神花以几乎固定的速度向外扩展，这个速度大概在每年12平方公里。但是近几年的数据显示，这个速度在快速下降。有预言，2020年，扩展将几乎停止。有学者指出，虽然扩展会停止，但已经复苏的区域将持续保持。另外利用其他技术修复废墟区域的研究也有进展。预计扩展停止后，对废墟净化的责任会留在幸存下来的我们的使命。
+ 源持续不断地向外扩散能子，能子遇到深渊时发生能变，消耗自身改变附近物质组成，产生复苏现象。受环境影响，能子在空间存在密度涨落分布，并有形成旋点，散点，敛点。能子密度对附近生物也会产生影响。通过对能子的研究，能子武器的概念被提出来，并进行实装化，以对付日益强大的深渊生物。能武核心是一个人工构造的能子场结构，主要利用旋点阵列对空间能子聚集存储，将存储起来的高密度能子进行固性后释放，以产生强大的能量。根据形态化的形式，产生的破坏力也不尽相同。理论上，这些能子也可用来治愈，但目前并没有获得实践上的进展。另外，怪物体内常常拥有比附近较高浓度的能子密度，这或许跟怪物持续对箱庭进攻的原因。
+ 神之花本质。神花是能子的源，复苏可以说是神花散射能子的结果。但这些能子是如何产生的？扩展的衰结意味着神花产生能子的速度在降低。一种猜想是神花能够通过某种方式将其他粒子转换成能子。这个观念一直持续了很久。只要弄明白这种方式，就可能制作出能子合成装置，即使扩展停止了，也能够以人工方式继续扩展，而且一旦能无限使用能子，其带来的价值是无法估量的。能子蕴含的能量远高于其他粒子，要持续产生高密度的能子流，一定要有提供能量的物质在。但在持续20年的实验结果中却展示神花附近没有任何耗散现象，这些能子就像是凭空产生的一样。（设定是：神之花是高维空间坍缩产生的。我们生活在三维空间，一个物体或者单属于它所在空间本身，或者是其更高维空间的投影。维度坍缩是指一个空间失去其自身的一个维度，并形成多个低维空间，探索期间会产生巨大的能量，这些能量会分布到形成的低维空间中去。根据能量的形式和大小会对低维空间产生不同的影响，甚至有可能破坏掉低维空间，使其继续向下坍缩。当一维空间发生坍缩时，空间自身结构即会消失，空间所有的能量都耗散到宇宙中。每次坍缩过程，大部分能量都会耗散入宇宙虚无中，空间自身即是一种结构。对空间的研究可以人工创造出小范围的空间，并且对其进行升维和降维操作。）
*** 怪物对策协会
+ 怪物百科全书出版。由怪物对策协会收集出版的全方面介绍怪物的历史第一本怪物百科全书出版了。只要买了它，再也不用害怕遇到怪物时不知所措，还在犹豫什么，赶紧买买买！本书全面的介绍了各种怪物的习性，出没地点，弱点。
+ 怪物在进化，并且进化速度在加快。利用已记录的数据，发现怪物在不断的进化，并形成类似人类的组织形式。其进攻频率和规模开始出现针对性，有策划性。并有出现一起进攻和一起撤退等行为。
+ 怪物存在自己的意识？！怪物很可能有自身的意识，有人类尝试与怪物相处，且并未被怪物吃掉。
+ 存在人型怪物的记录。具体信息仍不明。
*** 古代遗物
+ 自律人形。在混沌时代前，古人类文明制造的第四代量子机器人-概念试产型，只生产了一个。拥有完整自我意识，并记录了所有古人类文明，一直在世界游离。即使在深渊时代也存活了下来。箱庭世界诞生后，以普通人类的身份生活在箱庭。
+ 猫猫板。以可爱的猫形出名的VR移动终端。可以在网络范围内展开模拟现实空间。其主要原理是向网络上发射现实认证，根据虚拟空间信息大小，在获取到对应的认可数后，即可形成终端互联网络，进入互联网络的人所接触的信息会经由互联网络的加工，从而改变人所处的认识空间。

** 植物
+ 白茅
+ 狗尾巴草
+ 麦蒿
+ 莎草
+ 牛筋草
+ 车前草
+ 萤草
+ 七星灯
+ 红蘑菇
+ 蕨类
+ 白花
+ 大叶子
** 灌木乔木
+ 松柏
+ 三色树（绿，黄，红，叶子是丛状，中心散开四五片）
+ 圆球树（青蓝色，丛状圆形叶，中心颜色深，）
** 特殊资源
*** 力井
力井可以产生并存储着F能源，不能力井的最大存储量有一定差别，自然状态下，力井会自动恢复能源，直到溢出。力井可以被特定装置加以开发，以收集能源。开发过度会导致力井枯竭，枯竭的力井不会再聚集能源，最后消失。力井是神之花在改造大地过程中产生的能量回旋点，所有力井在整个循环中是连在一起的。
** 历史
*** 古代文明
*** 混沌时代
**** 神华改造大地
世界之初，天地昏暗混沌，不分日月。不知多少年后，大地上出现了一珠植物，命名为华，华出现时，方圆十公里地面出现物种复苏，最开始是灌木，然后是乔木和蕨类。在次之后，大地以每年5公里的速度扩展，大地低洼处形成河海，高耸处形成山地，平原，森林，沼泽也开始形成，各种动物也开始出现（苏醒）。每年的年末，生物会向这华的地方聚集，在一年的最后一天，华会发出宁静的光芒，动物们便围着华舞蹈。这样持续几十年后，大地已经形成了一片适宜生存的区域。
华纪元30年时，沉睡在废墟中的夏娃和亚当，在大地复苏中醒来，他们成为了人类的祖先。
*** 现代文明
**** 宗教
**** 科学
**** 政治
*** 角色
*** 能力
** 魔法
