// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: chat.proto

package proto

import (
	"cellnet"
	"reflect"
	_ "cellnet/codec/pb"
)

func init() {

	// chat.proto
	cellnet.RegisterMessageMeta("pb", "proto.CSChatText", reflect.TypeOf((*CSChatText)(nil)).Elem(), 288574792)
	cellnet.RegisterMessageMeta("pb", "proto.CSChatHistory", reflect.TypeOf((*CSChatHistory)(nil)).Elem(), 290593202)
	cellnet.RegisterMessageMeta("pb", "proto.SCChatText", reflect.TypeOf((*SCChatText)(nil)).Elem(), 192404384)
	cellnet.RegisterMessageMeta("pb", "proto.SCChatHistory", reflect.TypeOf((*SCChatHistory)(nil)).Elem(), 1240812751)

}
