// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat.proto
	game.proto
	login.proto
	role.proto
	struct.proto

It has these top-level messages:
	CSChatText
	CSChatHistory
	SCChatText
	SCChatHistory
	Echo
	SCNotice
	SCResponse
	SCError
	CSTokenLogin
	SCToken
	CSAccountLogin
	CSAccountCreate
	SCRoleList
	CSRoleCreate
	CSRoleDelete
	SCRoleCreate
	CSRoleLogin
	RoleCreate
	RoleBase
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CSChatText struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Channel int32  `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	To      int64  `protobuf:"varint,3,opt,name=to" json:"to,omitempty"`
}

func (m *CSChatText) Reset()                    { *m = CSChatText{} }
func (m *CSChatText) String() string            { return proto1.CompactTextString(m) }
func (*CSChatText) ProtoMessage()               {}
func (*CSChatText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CSChatText) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CSChatText) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *CSChatText) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

type CSChatHistory struct {
	Channel int32 `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *CSChatHistory) Reset()                    { *m = CSChatHistory{} }
func (m *CSChatHistory) String() string            { return proto1.CompactTextString(m) }
func (*CSChatHistory) ProtoMessage()               {}
func (*CSChatHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CSChatHistory) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

// ===========S2C=========
type SCChatText struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Channel int32  `protobuf:"varint,2,opt,name=Channel" json:"Channel,omitempty"`
	RoleId  int64  `protobuf:"varint,3,opt,name=RoleId" json:"RoleId,omitempty"`
	Date    uint32 `protobuf:"fixed32,4,opt,name=Date" json:"Date,omitempty"`
}

func (m *SCChatText) Reset()                    { *m = SCChatText{} }
func (m *SCChatText) String() string            { return proto1.CompactTextString(m) }
func (*SCChatText) ProtoMessage()               {}
func (*SCChatText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SCChatText) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SCChatText) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SCChatText) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *SCChatText) GetDate() uint32 {
	if m != nil {
		return m.Date
	}
	return 0
}

type SCChatHistory struct {
	Channel int32       `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	History *SCChatText `protobuf:"bytes,2,opt,name=history" json:"history,omitempty"`
}

func (m *SCChatHistory) Reset()                    { *m = SCChatHistory{} }
func (m *SCChatHistory) String() string            { return proto1.CompactTextString(m) }
func (*SCChatHistory) ProtoMessage()               {}
func (*SCChatHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SCChatHistory) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SCChatHistory) GetHistory() *SCChatText {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto1.RegisterType((*CSChatText)(nil), "proto.CSChatText")
	proto1.RegisterType((*CSChatHistory)(nil), "proto.CSChatHistory")
	proto1.RegisterType((*SCChatText)(nil), "proto.SCChatText")
	proto1.RegisterType((*SCChatHistory)(nil), "proto.SCChatHistory")
}

func init() { proto1.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3d, 0x6b, 0xc3, 0x30,
	0x10, 0x86, 0x91, 0x3f, 0xe9, 0x15, 0x17, 0xaa, 0xa1, 0x68, 0x14, 0x9a, 0x54, 0x0a, 0x1e, 0xda,
	0x9f, 0xa0, 0x0e, 0xed, 0x16, 0xe4, 0x90, 0x5d, 0x71, 0x04, 0x0a, 0x18, 0x29, 0x38, 0x37, 0x24,
	0xff, 0x3e, 0x20, 0xd9, 0xd8, 0x9e, 0x32, 0x49, 0x0f, 0x77, 0xaf, 0x9e, 0x17, 0x01, 0xf4, 0xce,
	0x60, 0x7b, 0x19, 0x03, 0x06, 0x5a, 0xc6, 0x43, 0xec, 0x00, 0x54, 0xa7, 0x9c, 0xc1, 0xbd, 0xbd,
	0x21, 0x65, 0x50, 0xf7, 0xc1, 0xa3, 0xf5, 0xc8, 0x08, 0x27, 0xf2, 0x45, 0xcf, 0x18, 0x27, 0xce,
	0x78, 0x6f, 0x07, 0x96, 0x71, 0x22, 0x4b, 0x3d, 0x23, 0x7d, 0x83, 0x0c, 0x03, 0xcb, 0x39, 0x91,
	0xb9, 0xce, 0x30, 0x88, 0x4f, 0x68, 0xd2, 0x8b, 0x7f, 0xe7, 0x2b, 0x86, 0xf1, 0xbe, 0x8e, 0x92,
	0x4d, 0x54, 0x0c, 0x00, 0x9d, 0x5a, 0xcb, 0xd5, 0x56, 0xae, 0x16, 0xb9, 0xda, 0xca, 0x27, 0xa4,
	0x1f, 0x50, 0xe9, 0x30, 0xd8, 0xff, 0xd3, 0x54, 0x60, 0x22, 0x4a, 0xa1, 0xf8, 0x35, 0x68, 0x59,
	0xc1, 0x89, 0xac, 0x75, 0xbc, 0x8b, 0x03, 0x34, 0xc9, 0xf6, 0xb4, 0x18, 0xfd, 0x82, 0xda, 0xa5,
	0xa5, 0x28, 0x7c, 0xfd, 0x7e, 0x4f, 0xbf, 0xd6, 0x2e, 0x75, 0xf5, 0xbc, 0x71, 0xac, 0xe2, 0xe8,
	0xe7, 0x11, 0x00, 0x00, 0xff, 0xff, 0x77, 0x77, 0xf0, 0x9f, 0x5e, 0x01, 0x00, 0x00,
}
