// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: game.proto

package proto

import (
	"cellnet"
	"reflect"
	_ "cellnet/codec/pb"
)

func init() {

	// game.proto
	cellnet.RegisterMessageMeta("pb", "proto.Echo", reflect.TypeOf((*Echo)(nil)).Elem(), 4915951)
	cellnet.RegisterMessageMeta("pb", "proto.SCNotice", reflect.TypeOf((*SCNotice)(nil)).Elem(), 217753131)
	cellnet.RegisterMessageMeta("pb", "proto.SCResponse", reflect.TypeOf((*SCResponse)(nil)).Elem(), 3322400903)
	cellnet.RegisterMessageMeta("pb", "proto.SCError", reflect.TypeOf((*SCError)(nil)).Elem(), 710920867)

}
