// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 测试Echo
type Echo struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *Echo) Reset()                    { *m = Echo{} }
func (m *Echo) String() string            { return proto1.CompactTextString(m) }
func (*Echo) ProtoMessage()               {}
func (*Echo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Echo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SCNotice struct {
	Index int32    `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Args  []string `protobuf:"bytes,2,rep,name=Args" json:"Args,omitempty"`
}

func (m *SCNotice) Reset()                    { *m = SCNotice{} }
func (m *SCNotice) String() string            { return proto1.CompactTextString(m) }
func (*SCNotice) ProtoMessage()               {}
func (*SCNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SCNotice) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SCNotice) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

// 默认响应
type SCResponse struct {
}

func (m *SCResponse) Reset()                    { *m = SCResponse{} }
func (m *SCResponse) String() string            { return proto1.CompactTextString(m) }
func (*SCResponse) ProtoMessage()               {}
func (*SCResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// 错误，0是无错误
type SCError struct {
	Error uint32 `protobuf:"varint,1,opt,name=Error" json:"Error,omitempty"`
}

func (m *SCError) Reset()                    { *m = SCError{} }
func (m *SCError) String() string            { return proto1.CompactTextString(m) }
func (*SCError) ProtoMessage()               {}
func (*SCError) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SCError) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func init() {
	proto1.RegisterType((*Echo)(nil), "proto.Echo")
	proto1.RegisterType((*SCNotice)(nil), "proto.SCNotice")
	proto1.RegisterType((*SCResponse)(nil), "proto.SCResponse")
	proto1.RegisterType((*SCError)(nil), "proto.SCError")
}

func init() { proto1.RegisterFile("game.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x0a, 0x5c, 0x2c, 0xae, 0xc9,
	0x19, 0xf9, 0x42, 0x12, 0x5c, 0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x09, 0x17, 0x47, 0xb0, 0xb3, 0x5f, 0x7e, 0x49, 0x66,
	0x72, 0xaa, 0x90, 0x08, 0x17, 0xab, 0x67, 0x5e, 0x4a, 0x6a, 0x05, 0x58, 0x0d, 0x6b, 0x10, 0x84,
	0x23, 0x24, 0xc4, 0xc5, 0xe2, 0x58, 0x94, 0x5e, 0x2c, 0xc1, 0xa4, 0xc0, 0xac, 0xc1, 0x19, 0x04,
	0x66, 0x2b, 0xf1, 0x70, 0x71, 0x05, 0x3b, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a,
	0xc9, 0x73, 0xb1, 0x07, 0x3b, 0xbb, 0x16, 0x15, 0xe5, 0x17, 0x81, 0x8c, 0x00, 0x33, 0xc0, 0x46,
	0xf0, 0x06, 0x41, 0x38, 0x49, 0x6c, 0x60, 0xd7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x30,
	0xbb, 0xd2, 0x30, 0xa2, 0x00, 0x00, 0x00,
}
