// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: login.proto

package proto

import (
	"cellnet"
	"reflect"
	_ "cellnet/codec/pb"
)

func init() {

	// login.proto
	cellnet.RegisterMessageMeta("pb", "proto.CSTokenLogin", reflect.TypeOf((*CSTokenLogin)(nil)).Elem(), 2546248961)
	cellnet.RegisterMessageMeta("pb", "proto.SCToken", reflect.TypeOf((*SCToken)(nil)).Elem(), 2177285887)
	cellnet.RegisterMessageMeta("pb", "proto.CSAccountLogin", reflect.TypeOf((*CSAccountLogin)(nil)).Elem(), 934430226)
	cellnet.RegisterMessageMeta("pb", "proto.CSAccountCreate", reflect.TypeOf((*CSAccountCreate)(nil)).Elem(), 2449379049)
	cellnet.RegisterMessageMeta("pb", "proto.SCRoleList", reflect.TypeOf((*SCRoleList)(nil)).Elem(), 3997033444)
	cellnet.RegisterMessageMeta("pb", "proto.CSRoleCreate", reflect.TypeOf((*CSRoleCreate)(nil)).Elem(), 1296019048)
	cellnet.RegisterMessageMeta("pb", "proto.CSRoleDelete", reflect.TypeOf((*CSRoleDelete)(nil)).Elem(), 1144617901)
	cellnet.RegisterMessageMeta("pb", "proto.SCRoleCreate", reflect.TypeOf((*SCRoleCreate)(nil)).Elem(), 722267877)
	cellnet.RegisterMessageMeta("pb", "proto.CSRoleLogin", reflect.TypeOf((*CSRoleLogin)(nil)).Elem(), 3425643116)

}
