// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GenderType int32

const (
	GenderType_Male   GenderType = 0
	GenderType_Female GenderType = 1
)

var GenderType_name = map[int32]string{
	0: "Male",
	1: "Female",
}
var GenderType_value = map[string]int32{
	"Male":   0,
	"Female": 1,
}

func (x GenderType) String() string {
	return proto1.EnumName(GenderType_name, int32(x))
}
func (GenderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type JobType int32

const (
	JobType_None JobType = 0
)

var JobType_name = map[int32]string{
	0: "None",
}
var JobType_value = map[string]int32{
	"None": 0,
}

func (x JobType) String() string {
	return proto1.EnumName(JobType_name, int32(x))
}
func (JobType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type CSTokenLogin struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *CSTokenLogin) Reset()                    { *m = CSTokenLogin{} }
func (m *CSTokenLogin) String() string            { return proto1.CompactTextString(m) }
func (*CSTokenLogin) ProtoMessage()               {}
func (*CSTokenLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CSTokenLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SCToken struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *SCToken) Reset()                    { *m = SCToken{} }
func (m *SCToken) String() string            { return proto1.CompactTextString(m) }
func (*SCToken) ProtoMessage()               {}
func (*SCToken) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *SCToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 帐号登录，成功返回SCRoleList
type CSAccountLogin struct {
	Id  string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Pwd string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
}

func (m *CSAccountLogin) Reset()                    { *m = CSAccountLogin{} }
func (m *CSAccountLogin) String() string            { return proto1.CompactTextString(m) }
func (*CSAccountLogin) ProtoMessage()               {}
func (*CSAccountLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CSAccountLogin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CSAccountLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

// 帐号注册，成功返回SCRoleList
type CSAccountCreate struct {
	Id  string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Pwd string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
}

func (m *CSAccountCreate) Reset()                    { *m = CSAccountCreate{} }
func (m *CSAccountCreate) String() string            { return proto1.CompactTextString(m) }
func (*CSAccountCreate) ProtoMessage()               {}
func (*CSAccountCreate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *CSAccountCreate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CSAccountCreate) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SCRoleList struct {
	Roles []*RoleBase `protobuf:"bytes,1,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *SCRoleList) Reset()                    { *m = SCRoleList{} }
func (m *SCRoleList) String() string            { return proto1.CompactTextString(m) }
func (*SCRoleList) ProtoMessage()               {}
func (*SCRoleList) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *SCRoleList) GetRoles() []*RoleBase {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CSRoleCreate struct {
	Name   string     `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Gender GenderType `protobuf:"varint,2,opt,name=Gender,enum=proto.GenderType" json:"Gender,omitempty"`
	Job    JobType    `protobuf:"varint,3,opt,name=Job,enum=proto.JobType" json:"Job,omitempty"`
}

func (m *CSRoleCreate) Reset()                    { *m = CSRoleCreate{} }
func (m *CSRoleCreate) String() string            { return proto1.CompactTextString(m) }
func (*CSRoleCreate) ProtoMessage()               {}
func (*CSRoleCreate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *CSRoleCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CSRoleCreate) GetGender() GenderType {
	if m != nil {
		return m.Gender
	}
	return GenderType_Male
}

func (m *CSRoleCreate) GetJob() JobType {
	if m != nil {
		return m.Job
	}
	return JobType_None
}

// 删除角色，返回错误码
type CSRoleDelete struct {
	Id int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *CSRoleDelete) Reset()                    { *m = CSRoleDelete{} }
func (m *CSRoleDelete) String() string            { return proto1.CompactTextString(m) }
func (*CSRoleDelete) ProtoMessage()               {}
func (*CSRoleDelete) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *CSRoleDelete) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SCRoleCreate struct {
	Role *RoleBase `protobuf:"bytes,1,opt,name=Role" json:"Role,omitempty"`
}

func (m *SCRoleCreate) Reset()                    { *m = SCRoleCreate{} }
func (m *SCRoleCreate) String() string            { return proto1.CompactTextString(m) }
func (*SCRoleCreate) ProtoMessage()               {}
func (*SCRoleCreate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *SCRoleCreate) GetRole() *RoleBase {
	if m != nil {
		return m.Role
	}
	return nil
}

type CSRoleLogin struct {
	Id int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *CSRoleLogin) Reset()                    { *m = CSRoleLogin{} }
func (m *CSRoleLogin) String() string            { return proto1.CompactTextString(m) }
func (*CSRoleLogin) ProtoMessage()               {}
func (*CSRoleLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *CSRoleLogin) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto1.RegisterType((*CSTokenLogin)(nil), "proto.CSTokenLogin")
	proto1.RegisterType((*SCToken)(nil), "proto.SCToken")
	proto1.RegisterType((*CSAccountLogin)(nil), "proto.CSAccountLogin")
	proto1.RegisterType((*CSAccountCreate)(nil), "proto.CSAccountCreate")
	proto1.RegisterType((*SCRoleList)(nil), "proto.SCRoleList")
	proto1.RegisterType((*CSRoleCreate)(nil), "proto.CSRoleCreate")
	proto1.RegisterType((*CSRoleDelete)(nil), "proto.CSRoleDelete")
	proto1.RegisterType((*SCRoleCreate)(nil), "proto.SCRoleCreate")
	proto1.RegisterType((*CSRoleLogin)(nil), "proto.CSRoleLogin")
	proto1.RegisterEnum("proto.GenderType", GenderType_name, GenderType_value)
	proto1.RegisterEnum("proto.JobType", JobType_name, JobType_value)
}

func init() { proto1.RegisterFile("login.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xdd, 0x4a, 0xfb, 0x40,
	0x10, 0xc5, 0x9b, 0xa6, 0x1f, 0xff, 0xff, 0x34, 0xa4, 0x71, 0xf5, 0x22, 0x08, 0x6a, 0x58, 0x15,
	0x6a, 0x2f, 0x7a, 0x91, 0x3c, 0x81, 0x46, 0x94, 0x96, 0x5a, 0x24, 0xe9, 0x0b, 0xe4, 0x63, 0x90,
	0x62, 0x9a, 0x2d, 0xc9, 0x16, 0xf1, 0xed, 0x65, 0x67, 0x57, 0x45, 0x51, 0xf0, 0x2a, 0x67, 0x66,
	0x7e, 0x3b, 0x67, 0x4e, 0x60, 0x54, 0x89, 0xa7, 0x4d, 0x3d, 0xdb, 0x35, 0x42, 0x0a, 0xd6, 0xa7,
	0xcf, 0xb1, 0xd3, 0xca, 0x66, 0x5f, 0x48, 0xdd, 0xe4, 0x17, 0xe0, 0xc4, 0xe9, 0x5a, 0x3c, 0x63,
	0xbd, 0x54, 0x28, 0x3b, 0x82, 0x3e, 0x55, 0xbe, 0x15, 0x58, 0x93, 0xff, 0x89, 0x2e, 0xf8, 0x19,
	0x0c, 0xd3, 0x98, 0xe4, 0x2f, 0x40, 0x08, 0x6e, 0x9c, 0x5e, 0x17, 0x85, 0xd8, 0xd7, 0x52, 0x2f,
	0x72, 0xa1, 0x3b, 0x2f, 0x0d, 0xd4, 0x9d, 0x97, 0xcc, 0x03, 0xfb, 0xf1, 0xa5, 0xf4, 0xbb, 0xd4,
	0x50, 0x92, 0x47, 0x30, 0xfe, 0x78, 0x13, 0x37, 0x98, 0x49, 0xfc, 0xd3, 0x23, 0x48, 0xe3, 0x44,
	0x54, 0xb8, 0xdc, 0xb4, 0x92, 0x5d, 0x42, 0x5f, 0xe9, 0xd6, 0xb7, 0x02, 0x7b, 0x32, 0x0a, 0xc7,
	0x3a, 0xd4, 0x4c, 0xf5, 0x6e, 0xb2, 0x16, 0x13, 0x3d, 0xe5, 0x42, 0x85, 0x54, 0xd2, 0xd8, 0x30,
	0xe8, 0xad, 0xb2, 0x2d, 0x1a, 0x23, 0xd2, 0xec, 0x0a, 0x06, 0xf7, 0x58, 0x97, 0xd8, 0x90, 0x9b,
	0x1b, 0x1e, 0x98, 0x5d, 0xba, 0xb9, 0x7e, 0xdd, 0x61, 0x62, 0x00, 0x16, 0x80, 0xbd, 0x10, 0xb9,
	0x6f, 0x13, 0xe7, 0x1a, 0x6e, 0x21, 0x72, 0x82, 0xd4, 0x88, 0x9f, 0xbe, 0x1b, 0xde, 0x62, 0x85,
	0x5f, 0x72, 0xd9, 0x2a, 0x17, 0x8f, 0xc0, 0xd1, 0x29, 0xcc, 0x41, 0xe7, 0xd0, 0x53, 0x15, 0x11,
	0x3f, 0xc4, 0xa0, 0x21, 0x3f, 0x81, 0x91, 0x5e, 0xfa, 0xfd, 0x07, 0xd3, 0xce, 0x29, 0x07, 0xf8,
	0xbc, 0x95, 0xfd, 0x83, 0xde, 0x43, 0x56, 0xa1, 0xd7, 0x61, 0x00, 0x83, 0x3b, 0xdc, 0x2a, 0x6d,
	0x4d, 0x0f, 0x61, 0x68, 0xee, 0x54, 0xc0, 0x4a, 0xd4, 0xe8, 0x75, 0xf2, 0x01, 0xb9, 0x45, 0x6f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xac, 0x70, 0xa9, 0x2d, 0x02, 0x00, 0x00,
}
