// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: role.proto

package proto

import (
	"cellnet"
	"reflect"
	_ "cellnet/codec/pb"
)

func init() {

	// role.proto
	cellnet.RegisterMessageMeta("pb", "proto.RoleCreate", reflect.TypeOf((*RoleCreate)(nil)).Elem(), 3169605473)

}
