// Generated by cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: role.proto

package roleproto

import (
	"cellnet"
	"reflect"
	_ "cellnet/codec/pb"
)

func init() {

	// role.proto
	cellnet.RegisterMessageMeta("pb", "roleproto.RoleBase", reflect.TypeOf((*RoleBase)(nil)).Elem(), 1385219412)

}
