// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: role.proto

package roleproto

import (
	"github.com/davyxu/cellnet"
	"reflect"
	_ "github.com/davyxu/cellnet/codec/pb"
)

func init() {

	// role.proto
	cellnet.RegisterMessageMeta("pb", "roleproto.RoleBase", reflect.TypeOf((*RoleBase)(nil)).Elem(), 1385219412)

}
