// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

/*
Package roleproto is a generated protocol buffer package.

It is generated from these files:
	role.proto

It has these top-level messages:
	RoleBase
*/
package roleproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoleBase struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Level int32  `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Sex   int32  `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	Name  string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *RoleBase) Reset()                    { *m = RoleBase{} }
func (m *RoleBase) String() string            { return proto.CompactTextString(m) }
func (*RoleBase) ProtoMessage()               {}
func (*RoleBase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RoleBase) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleBase) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RoleBase) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *RoleBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RoleBase)(nil), "roleproto.RoleBase")
}

func init() { proto.RegisterFile("role.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0xa5, 0x30, 0x2e, 0x8e,
	0xa0, 0xfc, 0x9c, 0x54, 0xa7, 0xc4, 0xe2, 0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xe6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x11, 0x2e, 0xd6, 0x9c, 0xd4, 0xb2, 0xd4,
	0x1c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x08, 0x47, 0x48, 0x80, 0x8b, 0xb9, 0x38, 0xb5,
	0x42, 0x82, 0x19, 0x2c, 0x06, 0x62, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0xb0,
	0x28, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0xe3, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb9, 0x42, 0x1e, 0x47, 0x77, 0x00, 0x00, 0x00,
}
